### ISSUE TITLE
Message de l'ajout dans la base de données 

### ISSUE THREAD

**Issue by Orogarde** [Flpichon/M2LCSHARP#1]
Bonjour ,
après analyse de votre code sur la page suivante : 
https://github.com/Flpichon/M2LCSHARP/blob/master/M2LCSHARP/Vues/ajout_adh.cs
j'ai observé le fait que, l'utilisateur n'a pas de moyen de savoir si l'adhérent a été ajouté ou non à la base de données.
je vous conseille de rajouter un messageBox contenant une alerte pour votre utilisateur qui l'informera du bon déroulement de la procédure .

**Comment by Flpichon** [comment]
Merci pour l’issue.
Je vais veiller à mettre en place un système d’alerte permettant de suivre le bon déroulement de l’ajout où de la modification d’un adhérent, ainsi que d’un club et d’un événement !

**Comment by Flpichon** [comment]
J'ai mis en place un système d'alerte lors de la création, suppression ou modification des données relatives à l'application
